# Generated by Django 4.2 on 2023-07-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customeradress'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='guest_user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
