# Generated by Django 4.2 on 2023-07-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accounts_guest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeradress',
            name='guest_user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
