# Generated by Django 4.2 on 2023-06-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogary',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catogary_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catogary_offer',
            new_name='category_offer',
        ),
    ]
