# Generated by Django 4.2 on 2023-07-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_rename_catogary_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Catogary',
            new_name='category',
        ),
    ]
