# Generated by Django 4.2 on 2023-07-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transcation_id',
            new_name='transaction_id',
        ),
    ]
